version: "3.8"

services:
    frontend:
        build: .
        container_name: "app_frontend_c"
        restart: on-failure
        ports:
            - "3000:3000"
        volumes:
            - /app/node_modules
            - ./:/app

        stdin_open: true
        tty: true
